name: Lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node_version: '13.x'

      - run: npm ci

      - name: Code Inspection
        uses: tinovyatkin/action-eslint@v1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          check-name: eslint