name: Build
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node_version: '13.x'

    - name: Cache Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Wait for code inspection
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-inspect
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: Lint

    - name: Build if inspect passes
      if: steps.wait-for-inspect.outputs.conclusion == 'success'

      run: |
        npm ci
        npm run build

      name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
